export {AUTHENTICATE_USER} from './AuthenticateUser.js'
export {ALL_USERS}  from './User.js'
export {CREATE_USER} from './User.js'
export {UPDATE_USER} from './User.js'
export {ALL_STUDENTS} from './User.js'
export {ALL_FACULTIES} from './User.js'
export {ALL_COURSES} from './Course.js'
export {CREATE_COURSE} from './Course.js'
export {DELETE_COURSE} from './Course.js'
export {ALL_STUDENTS_ONLY} from './User.js'
export {ADD_STUDENT_COURSE} from './Course.js'

export {CREATE_ASSIGNEMNT} from './Assignment.js'
export {CREATE_ASSIGNEMNT_GRADE} from './Assignment.js'
export {DELETE_ASSIGNMENT} from './Assignment.js'
export {ALL_ASSIGNMENTS} from './Assignment'